### PR TITLE
Add class styles to html and style css with media queries.Add images.

### LINKED ISSUE #16: Images for landing page

### PR DESCRIPTION
**Pull request by Amzzy78**
**Added styling to landing page**

### CODE REVIEW

**Review by MadStu — APPROVED** [review]

**Review by Polyanyanwu — COMMENTED** [review]
The brown background of the text seem to be too dark, the text is not easily read. Consider a lighter shade of brown

**Review by Amzzy78 — COMMENTED** [review]
Thank you.

**Comment by Amzzy78** [comment]
> The brown background of the text seem to be too dark, the text is not easily read. Consider a lighter shade of brown

Yes it is. Thank you for reviewing. I am going to carry on styling and correct that. Any other suggestions also very welcome.

**Comment by Polyanyanwu** [comment]
Also the nav bar need to be fixed to enable the user navigate to another section easily  Sent from Mail for Windows From: Amzzy78Sent: 13 November 2021 16:29To: Amzzy78/Check-your-pecsCc: Polycarp Anyanwu; Review requestedSubject: Re: [Amzzy78/Check-your-pecs] Add class styles to html and style css with media queries.Add images. (PR #18) The brown background of the text seem to be too dark, the text is not easily read. Consider a lighter shade of brownYes it is. Thank you for reviewing. I am going to carry on styling not and correct that. Any other suggestions also very welcome.—You are receiving this because your review was requested.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
